package:
  image: paperist/alpine-texlive-ja:latest
  command: ["–insecure-registry", “adaptive.u-aizu.ac.jp”]

  script:
    - apk --no-cache update
    - apk --no-cache add make aspell aspell-en
    - make -f docker.mk NO_ASPELL="true"
  artifacts:
    paths:
      - main.pdf
